### ISSUE TITLE
[BUG] Supervisor becomes zombie when child process stopped externally

### ISSUE THREAD

**Issue by kendru** [deref/exo#207] opened 2021-08-17 21:00 UTC
**Describe the bug**
When a process that is being supervised is stopped by some source other than the supervisor stopping it, the supervisor becomes a zombie process.

**To Reproduce**
1. Run some project in exo
2. Find the pid of one of the processes that exo is supervising
3. Send `SIGTERM` to that process.

The result is that the process is shown as stopped, but it is not able to be started again.

**Expected behavior**
The process exits, the supervisor exits, and the process state is cleaned up.

**Comment by kendru** [comment] 2021-08-18 15:58
I was trying to reproduce this yesterday afternoon, and I could not. I'll keep it open for now, but I am unassigning myself and noting that we do not have reliable repro steps.

**Comment by brandonbloom** [comment] 2021-09-03 23:47
Since this is not reproducible, I'm going to close it & if this ever happens again, hopefully we can get more details.

**Closed by brandonbloom** 2021-09-03 23:47 UTC
Labels: bug, supervisor, cannot reproduce
